### PR TITLE
test(review): cover lifecycle recovery bindings

### LINKED ISSUE #1928: review finalize enters operation_outcome_unknown and cannot bind maintainer repair authorization
## Pre-flight Checklist

- [x] I have searched [existing issues](https://github.com/Gentleman-Programming/gentle-ai/issues) and this is not a duplicate.
- [x] I understand that PRs will be rejected if the linked issue does not have `status:approved`.

## 📝 Bug Description

`review finalize` reached the generic `operation_outcome_unknown` classification when compact-authority validation raised an inexact recovery-authorization binding error. The operation had not started mutating authority, so reporting an unknown mutation outcome was incorrect and left the caller without a typed recovery route.

PR #1936 addresses this classification defect. A second, separate blocker was discovered during reproduction: the corrupt binding has no sanctioned quarantine/recovery path and therefore blocks unrelated reviews repository-wide. That missing operation is tracked as dependency #2014.

## 🔄 Steps to Reproduce

1. In a Git repository whose shared compact-authority store contains the invalid edge shown below, run the original finalization command:

```sh
gentle-ai review finalize \
  --cwd /Users/psapoznik/Proyectos/Proyectos/NovaERP-pr1032-comments \
  --lineage review-4ca34274d919fd55 \
  --captured-results \
  --validation /tmp/review-4ca34274d919fd55-fix-validation.json \
  --evidence /tmp/review-4ca34274d919fd55-final-evidence-v2.json
```

2. Observe the generic defect classification `operation_outcome_unknown`.
3. Reproduce/inspect on current v2.2.2:

```sh
gentle-ai review inspect-authority --cwd /Users/psapoznik/Proyectos/Proyectos/NovaERP-pr1079-comments
```

4. Attempting an unrelated `review start` also fails on the same corrupt edge.

## ✅ Expected Behavior

The compact recovery authorization mismatch is classified deterministically before mutation begins, with a typed code and actionable next step. No `operation_outcome_unknown` report should be produced for a validation failure known to occur before native mutation.

## ❌ Actual Behavior

On v2.2.0, `review finalize` emitted:

```text
invalid compact authority graph: escalated recovery requires an exact maintainer authorization binding (projection=workspace target_identity=sha256:ab75da4a766ab097a7e6b1498d1254546e484b12b2ea08242dc7424b7c99cb1a)
reason_code: operation_outcome_unknown
operation: review.finalize
phase: native_running
```

The generated defect report incorrectly described the true mutation outcome as unknown. PR #1936 correctly identifies that classification issue. The underlying corrupt edge still has no sanctioned exit; see #2014.

## Environment

- **Faulting binary:** Gentle AI v2.2.0
- **Faulting commit:** `ee83e83d56f0d149c52f93fd13b3296858f5147f`
- **Current reproduction binary:** Gentle AI v2.2.2
- **Current release commit:** `09c2d8b6369860058aa44704df76b1b33c745675`
- **OS:** macOS arm64
- **AI Agent / Client:** Codex
- **Affected Area:** CLI (commands, flags)
- **Repository root:** `/Users/psapoznik/Proyectos/Proyectos/NovaERP`
- **Worktree used for current inspection:** `/Users/psapoznik/Proyectos/Proyectos/NovaERP-pr1079-comments`
- **Shared compact store:** 65 entries, 3 edges, 1 invalid edge

## Complete machine-readable `inspect-authority` output

```json
{
  "schema": "gentle-ai.review-authority-inspection/v1",
  "operation": "review/inspect-authority",
  "repository_root": "/Users/psapoznik/Proyectos/Proyectos/NovaERP-pr1079-comments",
  "complete": true,
  "valid": false,
  "totals": {
    "compact_entries": 65,
    "loaded_entries": 65,
    "edges": 3,
    "valid_edges": 2,
    "invalid_edges": 1,
    "entry_diagnostics": 0
  },
  "edges": [
    {
      "predecessor_lineage_id": "review-86268158775b2b8a",
      "recorded_predecessor_revision": "sha256:776a062be62451f6a74e98096f1d710e6421380ed62726a7027e5e0d01c8ecf2",
      "observed_predecessor_revision": "sha256:776a062be62451f6a74e98096f1d710e6421380ed62726a7027e5e0d01c8ecf2",
      "successor_lineage_id": "review-928c0ffee0dd2026",
      "successor_revision": "sha256:fb4e0f8e1adce6a5171d2324f750d955a64f9ea4c9d3f98501d21cb487606d3d",
      "valid": true,
      "anomaly_classes": [],
      "problems": []
    },
    {
      "predecessor_lineage_id": "review-928c0ffee0dd2026",
      "recorded_predecessor_revision": "sha256:fb4e0f8e1adce6a5171d2324f750d955a64f9ea4c9d3f98501d21cb487606d3d",
      "observed_predecessor_revision": "sha256:fb4e0f8e1adce6a5171d2324f750d955a64f9ea4c9d3f98501d21cb487606d3d",
      "successor_lineage_id": "review-928c0ffee0dd2027",
      "successor_revision": "sha256:0ad001e5ee66028069dfb1eedf708c7df76f24dc9a12d53aabbbca147cecb880",
      "valid": false,
      "anomaly_classes": [],
      "problems": [
        "escalated recovery requires an exact maintainer authorization binding (projection=workspace target_identity=sha256:ab75da4a766ab097a7e6b1498d1254546e484b12b2ea08242dc7424b7c99cb1a)"
      ],
      "non_reconcilable_reason": "successor \"review-928c0ffee0dd2027\" records a gentle-ai.review-recovery-authorization/v1 binding bound to different content; that is corruption, not a pre-contract authorization"
    },
    {
      "predecessor_lineage_id": "review-deb046914ddea686",
      "recorded_predecessor_revision": "sha256:40a9e373debab74bd3363829252735c16162407b119d5fd46cefadb1f306033c",
      "observed_predecessor_revision": "sha256:40a9e373debab74bd3363829252735c16162407b119d5fd46cefadb1f306033c",
      "successor_lineage_id": "review-f15ca1c0a77e8e22",
      "successor_revision": "sha256:72a34eefea42827aedec6d2be6954dba645a5a370ec6794106c0ab9e52adac76",
      "valid": true,
      "anomaly_classes": [],
      "problems": []
    }
  ],
  "entry_diagnostics": [],
  "sanctioned_exits": [
    {
      "successor_lineage_id": "review-928c0ffee0dd2027",
      "blocked": "no advertised operation admits this edge: reconciliation does not classify it into a supported anomaly class, and `review abandon` does not accept the successor. Nothing quarantines this shape today, so no command clears it and the entry stays exactly as persisted. This report, with non_reconcilable_reason, is the artifact to escalate"
    }
  ]
}
```

## Predecessor, successor and binding metadata

- predecessor lineage: `review-928c0ffee0dd2026`
- recorded predecessor revision: `sha256:fb4e0f8e1adce6a5171d2324f750d955a64f9ea4c9d3f98501d21cb487606d3d`
- observed predecessor revision: `sha256:fb4e0f8e1adce6a5171d2324f750d955a64f9ea4c9d3f98501d21cb487606d3d`
- successor lineage: `review-928c0ffee0dd2027`
- successor revision: `sha256:0ad001e5ee66028069dfb1eedf708c7df76f24dc9a12d53aabbbca147cecb880`
- binding schema: `gentle-ai.review-recovery-authorization/v1`
- projection: `workspace`
- required target identity: `sha256:ab75da4a766ab097a7e6b1498d1254546e484b12b2ea08242dc7424b7c99cb1a`
- complete non-reconcilable reason: `successor "review-928c0ffee0dd2027" records a gentle-ai.review-recovery-authorization/v1 binding bound to different content; that is corruption, not a pre-contract authorization`

## Additional Context

- Classification fix: PR #1936.
- Missing quarantine/recovery dependency: #2014.
- The corruption blocks unrelated reviews in the same Git common-dir, including validated ERP follow-ups #1032 and #1079.

### PR DESCRIPTION
**Pull request by mtriggiano**
## 🔗 Linked Issue

Closes #1928

## 🏷️ PR Type

- [x] `type:chore` — Build, CI, or tooling changes

## 📝 Summary

- Add end-to-end regression coverage for correction evidence bindings.
- Prove escalated recovery stays stopped until the candidate changes and a maintainer explicitly authorizes recovery.
- Exercise the exact native transition through the recovered fresh lineage.

## 📂 Changes

| File / Area | What Changed |
|-------------|-------------|
| `internal/cli/review_next_transition_test.go` | Executes the emitted correction evidence transition and verifies the accepted fix-diff target identity. |
| `internal/cli/review_recovery_target_kind_test.go` | Covers unchanged escalation stop and changed-candidate maintainer-authorized recovery. |

## 🧪 Test Plan

- [x] Focused changed lifecycle regressions pass.
- [x] Related CLI lifecycle suites pass.
- [x] Related review-transaction suites pass.
- [x] `git diff --check` passes.
- [ ] Full `go test ./internal/cli -count=1` completed; it timed out at 120s and 300s without reporting a failure.
- [ ] E2E Docker suite; not required for this test-only lifecycle coverage and left to CI.

## ✅ Contributor Checklist

- [x] PR is linked to approved issue #1928.
- [x] PR stays within 400 changed lines.
- [x] Exactly one `type:*` label will be applied.
- [x] Focused and related tests pass.
- [x] Documentation is not required for this test-only change.
- [x] Commit follows Conventional Commits.
- [x] Commit contains no `Co-Authored-By` trailer.

## 💬 Notes for Reviewers

The production lifecycle fixes are already on `main`. This PR prevents regressions by executing the native transitions that previously failed in real workflows.

## Summary by CodeRabbit

* **Tests**
  * Added end-to-end coverage for corrected validation flows, including evidence capture and transition execution.
  * Added coverage ensuring escalated reviews require a changed target and explicit recovery authorization before proceeding.

### CODE REVIEW

**Comment by mtriggiano** [comment]
The PR is linked to approved issue #1928 and contains test-only lifecycle regression coverage. I do not have permission to update labels on the upstream PR. Please remove `slop` and apply exactly one `type:chore` label so the contribution gate can evaluate it correctly.

**Review by dnlrsls — CHANGES_REQUESTED** [review]
Please remove or repoint `Closes #1928`: this test-only change does not implement the failure-classification defect approved in #1928, which is addressed by #1936. Add exactly one appropriate `type:*` label, complete the required PR-template test/checklist entries, and obtain the project CI checks before reconsideration.

**Review by dnlrsls — CHANGES_REQUESTED** [review]
Changes requested: linked issue #1928 is open with `status:needs-info` and is not approved. Please provide the outstanding concrete information and obtain `status:approved` before implementation review resumes.

**Comment by Alan-TheGentleman** [comment]
Thanks for taking the time to contribute. After review, this PR doesn't meet the contribution bar for the repo — the change reads as largely generated output without the validation evidence our workflow requires (see CONTRIBUTING.md: focused scope, failing regression first, benchmark/test evidence in the Test Plan). Closing it as part of backlog triage.

If you want to pursue this, the path forward is: pick up the linked issue (or open one and wait for status:approved), start from a failing test that reproduces the problem, and keep the diff scoped to that mechanism. Happy to review a focused follow-up.
