### PR TITLE
feat(agents/claude): add native SDD sub-agents with per-phase model assignment

### LINKED ISSUE #335: feat(agents/claude): add native SDD sub-agents with per-phase model assignment
### Pre-flight Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I understand that PRs will be rejected if the linked issue does not have `status:approved`

### 🔍 Affected Area

Installation Pipeline

### 💡 Problem Statement

Claude Code officially supports native sub-agents in `~/.claude/agents/*.md` with frontmatter (`name`, `description`, `tools`, `model`) — it's the flagship orchestration feature of the CLI. `gentle-ai` already computes a per-phase SDD model assignment in `internal/components/sdd/inject.go:1230-1325` (Opus for `propose`/`design`, Sonnet for `spec`/`tasks`, Haiku for `archive`) and renders it as a markdown table inside `internal/assets/claude/sdd-orchestrator.md`.

Today that information lives **only as text**. The Claude adapter at `internal/agents/claude/adapter.go` does not implement the optional `subAgentInjector` interface (defined in `internal/components/sdd/inject.go:72-80`), so no sub-agent files are written to `~/.claude/agents/`. Meanwhile the Cursor (`internal/agents/cursor/adapter.go:144`), Kimi (`internal/agents/kimi/adapter.go:209`), and Kiro (`internal/agents/kiro/adapter.go:115`) adapters **do** implement it. Claude — the flagship agent in the catalog — does not.

Consequences for users of Claude Code:
- No native agent switching from the Claude Code UI per SDD phase.
- The per-phase model contract lives as prose inside the orchestrator markdown with no enforcement — it depends entirely on the orchestrator remembering to read the table.
- The existing `ClaudeModelAssignments` feature (introduced in #217) is effectively dead weight for Claude — it is rendered but never wired to a real capability.

Additionally, the `SupportsSubAgents()` method is duplicated as an ad-hoc optional interface in **three** separate places:

- `internal/components/sdd/inject.go:72` (`subAgentInjector`)
- `internal/components/uninstall/service.go:68` (`subAgentCapability`)
- `internal/cli/run.go:973`

Every new adapter that wants native sub-agents must re-declare the same method set. This is drift that will keep growing as more adapters adopt the pattern.

### 📦 Proposed Solution

Two coordinated changes:

**1. Add native sub-agents for Claude Code**

- Create `internal/assets/claude/agents/sdd-{explore,propose,spec,design,tasks,apply,verify,archive}.md` (8 files), each with frontmatter:
  ```yaml
  ---
  name: sdd-<phase>
  description: <phase-specific description>
  tools: <scoped toolset per phase>
  model: {{CLAUDE_MODEL}}
  ---
  ```
- Implement in `internal/agents/claude/adapter.go`:
  - `SupportsSubAgents() bool` → `true`
  - `SubAgentsDir(homeDir) string` → `~/.claude/agents`
  - `EmbeddedSubAgentsDir() string` → `claude/agents`
- Extend the existing placeholder resolver at `internal/components/sdd/inject.go:567-585` to resolve `{{CLAUDE_MODEL}}` against `opts.ClaudeModelAssignments` — symmetric to the current `{{KIRO_MODEL}}` handling.

**2. Formalize `SupportsSubAgents()` into the main `Adapter` interface**

- Move the three methods (`SupportsSubAgents`, `SubAgentsDir`, `EmbeddedSubAgentsDir`) from optional interfaces into `internal/agents/interface.go`.
- Adapters that do not support sub-agents return `(false, \"\", \"\")` — zero behavior change.
- Remove the duplicated interface declarations at `sdd/inject.go:72`, `uninstall/service.go:68`, and `cli/run.go:973` — consolidate to a single source of truth.

**Tests / verification**

- Golden tests for the 8 generated sub-agent files resolving correctly under `ClaudeModelPresetBalanced` and any custom `ClaudeModelAssignments`.
- Unit test for `SupportsSubAgents() == true` on the Claude adapter.
- E2E check that `~/.claude/agents/sdd-*.md` exist after an SDD-enabled install.

**Estimated scope**: ~1300 LOC across ~20 files (Go + embedded markdown + tests).

### ⚖️ Why native sub-agents over the current `general-purpose` + runtime `model:` override

The existing orchestration in `~/.claude/CLAUDE.md` already reads a Model Assignments table at session start, caches `phase → alias`, and passes the alias via the `model:` parameter on every `Agent` tool call against `subagent_type: "general-purpose"`. **Model switching is already working today** — this proposal is not about enabling it. What it changes is *where the contract lives* and *how much the orchestrator has to carry*:

| Aspect | Today (`general-purpose` + runtime override) | With this proposal (native `sdd-*` sub-agents) |
|---|---|---|
| Model assignment | Prose table in CLAUDE.md; orchestrator reads + caches + re-passes `model:` on every call | Baked into the sub-agent frontmatter — Claude Code applies it automatically |
| Invocation shape | `Agent(subagent_type: "general-purpose", model: "opus", prompt: "You are sdd-propose, read ~/.claude/skills/sdd-propose/SKILL.md...")` | `Agent(subagent_type: "sdd-propose", prompt: "<task context only>")` |
| Failure mode if orchestrator forgets `model:` | Silently runs under Sonnet default — archive phase ~10× more expensive with no visible error | Impossible to forget — the model is contractual, enforced by the runtime |
| Tool surface per phase | All built-in tools available to every phase (no scoping) | Allowlist per phase via `tools:` frontmatter — read-only phases physically cannot Edit/Write/Bash |
| Recursive delegation | Nothing prevents a phase from spawning another `Task` by mistake | `Task` excluded from every phase's allowlist — Claude Code refuses the call |
| Discoverability | `/agents` picker shows only `general-purpose` | `/agents` picker shows all 8 `sdd-*` phases with descriptions |
| Prompt versioning | Phase role/instructions re-injected by orchestrator on every call | Phase role travels with the agent file — update once, applied everywhere |

**Token footprint.** Per delegation, the new path is equivalent or slightly cheaper:
- The invocation prompt shrinks because the role/skill-reference that used to be re-injected on every call now lives inside the agent's own system prompt (authored once, loaded once).
- The tool schema payload shrinks for read-only phases — 3–4 tool schemas loaded instead of the full built-in set.
- The orchestrator no longer needs to cache and re-pass the `model:` parameter, so its per-session bookkeeping drops.

Rough estimate across a full SDD cycle (8 phases): on the order of thousands of tokens saved vs the current path, plus the deterministic model assignment eliminates the silent-cost failure mode where the orchestrator forgets to pass `model: haiku` to archive.

### 🔄 Alternatives Considered

- **Keep the status quo** — continue using `subagent_type: "general-purpose"` with runtime `model:` overrides driven by the CLAUDE.md table. Rejected: the table is correct but it lives *outside* the agent, meaning every invocation depends on the orchestrator remembering to apply it. Native sub-agents move the contract inside the runtime where it cannot be bypassed, and add tool scoping as a bonus (see comparison above).
- **Add sub-agents without formalizing the interface** — leaves the three duplicated optional interfaces in place. Rejected: the next adapter to adopt sub-agents will replicate the pattern ad-hoc; this issue is the right moment to consolidate.
- **Use skills instead of sub-agents for phase specialization** — skills already work. Rejected: skills cannot set a per-phase `model:` frontmatter, which is the core reason sub-agents are the right primitive here.

### 📎 Additional Context

**Existing related issues**

- **#217** (closed) — `feat(sdd): SDD model profiles — assign different AI models per SDD phase`. This introduced the `ClaudeModelAssignments` machinery. The proposal in this issue **builds directly on top** of #217 and finally turns it into a concrete capability for Claude users.
- **#222** (closed, implemented) — `feat(agent-builder): TUI flow for creating custom AI sub-agents`. Adjacent: #222 lets users build custom sub-agents via TUI. This issue is the complementary side — shipping opinionated **pre-built SDD sub-agents** for Claude out of the box.
- **#213** (closed) — `feat(agents): AGENT.md frontmatter — project-scoped specialized agents with role, model, and tool constraints`. Prior art for the frontmatter shape proposed here (`model:`, `tools:`, `description:`).
- **#184** (open) — `Añadir Fallback a los modelos elegidos para las fases de SDD`. Complementary: once sub-agents carry a resolved `model:` in frontmatter, the fallback logic from #184 can target it directly.
- **#128** (open, approved) — `feat(architecture): separate multi-agent and single-agent skill distribution with delegation model awareness`. Architectural neighbor — the interface consolidation proposed here removes one source of drift before #128 lands.

**Platform precedent**

- Cursor, Kimi, and Kiro already ship native sub-agents via the same `subAgentInjector` contract. Kimi v1.21.0 (`internal/assets/kimi/agents/`) uses YAML+MD pairs; Kiro uses a `{{KIRO_MODEL}}` placeholder resolved at install time — that exact pattern is what this issue proposes for `{{CLAUDE_MODEL}}`.

**Split strategy**

This issue is the first of a three-part series of Claude Code integration improvements I plan to propose. The other two (separate issues, opened after this one) will cover:
- Engram `SessionStart` / `Stop` hooks in `~/.claude/settings.json` (zero-friction memory protocol)
- Slash commands + meta-commands (`/sdd-new`, `/sdd-ff`, `/sdd-continue`) via `~/.claude/commands/`

Each piece will be its own PR to keep reviews focused.

### PR DESCRIPTION
**Pull request by GerardoFC8**
Closes #335

## Summary

First half of the work proposed in #335 — the capability and assets needed to ship native SDD sub-agents for Claude Code, with per-phase model enforcement and scoped tool allowlists driven by `opts.ClaudeModelAssignments`.

Four focused commits:

1. **`feat(agents/claude)`** — implements `SupportsSubAgents`, `SubAgentsDir`, `EmbeddedSubAgentsDir`, and `ClaudeModelID` on the Claude adapter. Claude Code accepts `opus`/`sonnet`/`haiku` verbatim so `ClaudeModelID` is an identity over `alias.String()`, but the method gates the type assertion in the SDD injector.
2. **`feat(assets/claude)`** — ships `internal/assets/claude/agents/sdd-{explore,propose,spec,design,tasks,apply,verify,archive}.md` (8 files). Frontmatter carries a `{{CLAUDE_MODEL}}` sentinel. Bodies follow the existing Cursor sub-agent shape, rewritten to point at `~/.claude/skills/<phase>/`.
3. **`feat(sdd)`** — adds the `claudeModelResolver` optional interface symmetric to the existing `kiroModelResolver` and extends the sub-agent copy loop in `internal/components/sdd/inject.go` to substitute `{{CLAUDE_MODEL}}` against `opts.ClaudeModelAssignments` (with `default` fallback and `ClaudeModelSonnet` safety default).
4. **`feat(assets/claude)` tools scoping** — every sub-agent declares an explicit `tools:` allowlist in frontmatter so Claude Code enforces phase boundaries at the runtime layer. Read-only phases (explore, propose, spec, design, tasks) cannot Edit/Write/Bash. Only sdd-apply can modify code. None carry `Task`, so recursive delegation is impossible.

## Why native sub-agents over the existing `general-purpose` + runtime `model:` override

The existing SDD orchestration in `~/.claude/CLAUDE.md` already reads a Model Assignments table at session start, caches `phase → alias`, and passes the alias via the `model:` parameter on every `Agent` tool call against `subagent_type: "general-purpose"`. Model switching was already working. What this PR changes is **where the contract lives** and **how much the orchestrator has to carry**:

| Aspect | Today (`general-purpose` + runtime override) | With this PR (native `sdd-*` sub-agents) |
|---|---|---|
| Model assignment | Lives as prose table in CLAUDE.md; orchestrator reads + caches + passes `model:` on every call | Baked into the sub-agent frontmatter (`model:`) — Claude Code applies it automatically |
| Invocation shape | `Agent(subagent_type: "general-purpose", model: "opus", prompt: "You are sdd-propose, read ~/.claude/skills/sdd-propose/SKILL.md...")` | `Agent(subagent_type: "sdd-propose", prompt: "<task context only>")` |
| Failure mode if orchestrator forgets `model:` | Runs under Sonnet default — archive phase silently 10× more expensive | Impossible to forget — model is contractual |
| Tool surface per phase | All built-in tools available to every phase (no scoping) | Allowlist per phase via `tools:` frontmatter — read-only phases physically cannot Edit/Write/Bash |
| Recursive delegation | Nothing prevents a phase from spawning another `Task` by mistake | `Task` excluded from every phase's allowlist — Claude Code refuses the call |
| Discoverability | `/agents` picker shows only `general-purpose` | `/agents` picker shows all 8 `sdd-*` phases with descriptions |
| Prompt versioning | Phase role/instructions re-injected by orchestrator on every call | Phase role travels with the agent file — update once, applied everywhere |

Net effect: the orchestrator gets thinner, the phase contract gets stronger, and an entire class of "orchestrator forgot to X" bugs becomes unreachable.

### Token footprint

Per delegation, the new path is roughly equivalent or slightly cheaper:
- **Invocation prompt shrinks** because the role/skill-reference that used to be re-injected on every call now lives inside the agent's own system prompt (authored once, loaded once).
- **Tool schema payload shrinks** for read-only phases — 3–4 tools loaded instead of the full built-in set (~10–12).
- **Model-parameter caching in the orchestrator** becomes unnecessary, so the orchestrator-side setup cost drops.

Rough estimate across a full SDD cycle (8 phases): on the order of thousands of tokens saved vs the current path, plus the deterministic model assignment eliminates the silent-cost failure mode where the orchestrator forgets to pass `model: haiku` to archive.

## Still to land on this PR (follow-up commits)

Scoped to the same issue #335:

- [ ] **Formalize `SupportsSubAgents` / `SubAgentsDir` / `EmbeddedSubAgentsDir` into `internal/agents/interface.go`** — today it's duplicated as optional-interface types in three places (`sdd/inject.go:72`, `uninstall/service.go:68`, `cli/run.go:973`). Consolidating into the main `Adapter` interface with no-op stubs on non-subagent adapters.
- [ ] **Golden tests** for the generated Claude agent files under `ClaudeModelPresetBalanced` and a custom assignment map. Planning to add a dedicated section under `testdata/golden/` and update `internal/components/golden_test.go` to assert them.

Splitting this way so each step is reviewable on its own; neither follow-up affects runtime behavior shipped in commits 1–4.

## Test plan

- [x] `go test ./...` passes locally after each commit (no short-mode skips touch the changed packages).
- [x] New unit test: `internal/agents/claude/adapter_test.go::TestAdapter_SubAgentCapability` — asserts the three adapter methods return the expected values.
- [x] New integration test: `internal/components/sdd/inject_test.go::TestInjectClaudeSubAgentsResolveModels` — drives `Inject()` with a custom `ClaudeModelAssignments` map and asserts the resulting `~/.claude/agents/sdd-{design,archive,spec}.md` files carry `model: opus`, `model: haiku`, `model: sonnet` respectively (sonnet via the `default` fallback).
- [x] New integration test: `internal/components/sdd/inject_test.go::TestInjectClaudeSubAgentsScopedTools` — asserts each phase carries the expected `tools:` allowlist and denies unsafe tools (explore/propose cannot Edit/Write/Bash; no phase carries Task).
- [ ] Golden coverage (pending on follow-up commit).
- [ ] E2E: `cd e2e && ./docker-test.sh` — will run before marking ready-for-review.

## Notes

- Tests pass cleanly against the full `go test ./...` suite. No golden baselines needed updating in this chunk because the existing Claude goldens (`persona-claude-gentleman.golden`, `combined-claude-claudemd.golden`) cover persona/CLAUDEMD assembly, which is untouched here.
- No changes to uninstall behavior — the existing optional-interface path in `uninstall/service.go:599` already covers Claude now that the adapter implements the trio. Uninstall will correctly clean up `~/.claude/agents/` on removal.
- Following `CONTRIBUTING.md`: conventional commits, branch name matches the enforced pattern, no `Co-Authored-By` attribution.

### CODE REVIEW

**Comment by Alan-TheGentleman** [comment]
Added a follow-up commit to finish the runtime contract for Claude native SDD agents:\n\n- planning phases () now have the minimal / access needed to persist openspec artifacts\n- Claude phase agents now expose only the Engram MCP tools they actually use (, , , plus  for )\n- updated Claude tool-scope tests and regenerated goldens accordingly\n\nValidated locally with:\n- ok  	github.com/gentleman-programming/gentle-ai/internal/components/sdd	(cached)\n- ok  	github.com/gentleman-programming/gentle-ai/internal/components	0.236s\n- ok  	github.com/gentleman-programming/gentle-ai/internal/components	3.052s
ok  	github.com/gentleman-programming/gentle-ai/internal/components/engram	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/filemerge	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/gga	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/mcp	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/permissions	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/persona	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/sdd	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/skills	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/theme	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/components/uninstall	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/antigravity	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/claude	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/codex	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/cursor	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/gemini	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/kilocode	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/kimi	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/kiro	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/opencode	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/qwen	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/vscode	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/agents/windsurf	(cached)
ok  	github.com/gentleman-programming/gentle-ai/internal/cli	(cached)\n-
