### PR TITLE
fix(sdd): keep stale verify evidence out of remediation

### LINKED ISSUE #2137: bug(sdd): passing verify stays blocked at resolve-review — verify total 11 does not match actual requirement count 0; bounded review transaction is missing (v2.2.4)
### Pre-flight Checklist

- [x] I have searched [existing issues](https://github.com/Gentleman-Programming/gentle-ai/issues) and this is not a duplicate
- [x] I understand that PRs will be rejected if the linked issue does not have `status:approved`

### Pre-flight Checklist

- [x] I have searched existing issues and this is not a duplicate
- [x] I understand that PRs will be rejected if the linked issue does not have `status:approved`

### Bug Description

Gentle AI v2.2.4 leaves an OpenSpec SDD change permanently blocked at `resolve-review` even though the verification is a PASS and every task is complete. The dispatcher reports two blockers:

```text
- bound compact post-apply gate context changed
- verify evidence cannot enter remediation: verify result total 11 does not match actual requirement count 0; bounded review transaction is missing
The change is archive-ready on its merits (all tasks complete; passing gentle-ai.verify-result/v1 with verdict pass, 11 requirements, 16 scenarios; build and test gates green), but the native dispatcher computes actual requirement count 0 even though the delta spec contains 11 clearly formatted requirements, and it demands a "bounded review transaction" for a PASS result that the compact model never creates.
Observed facts (no root cause asserted):
- The change delta spec exists at openspec/changes/<change>/specs/<component>/spec.md in standard OpenSpec delta format (## MODIFIED Requirements, ## ADDED Requirements, ### REQ-XX:), containing 11 requirements.
- The repository has no openspec/projects/ directory at all — the target project spec has never been materialized (archive is the phase that syncs deltas, and archive is blocked).
- verify-report.md declares requirements: 11/11, scenarios: 16/16, verdict: pass, zero blockers.
- gentle-ai review repair reports status: unsupported with 0 lineages/events/eligible candidates; supported operations are only review/complete-fix and review/validate-fix with no candidates.
- gentle-ai review status --cwd <repo> --contract gentle-ai.review-integration/v2 --next-transition reports applicability: unrelated / receipt.status: not_applicable and offers only review.start for the current workspace snapshot, which does not clear the SDD dispatcher block.
- Review mode is ENABLED (receipt-driven development: on), so the disabled-mode archive deadlock (#2128) is not the applicable seam.

### 🔄 Steps to Reproduce

1. Start an OpenSpec SDD change for a component that has never been archived — no openspec/projects/<component>/spec.md exists.
2. Complete proposal, delta spec (## MODIFIED Requirements / ## ADDED Requirements, e.g. 11 requirements), design, tasks, and implementation; all task checkboxes complete.
3. Persist a passing verify-report.md with schema gentle-ai.verify-result/v1, verdict: pass, requirements: 11/11, scenarios: 16/16, zero blockers, green build/test exit codes.
4. Run gentle-ai sdd-status <change> --cwd <repo> --json --instructions.


### ✅ Expected Behavior

A passing verification with all tasks complete should not enter failed-verification remediation at all. sdd-status should route toward archive readiness (or at least verify for a fresh re-run) instead of resolve-review. The dispatcher should not demand a "bounded review transaction" for a PASS result, and a first-time component with no materialized project spec should not be counted as 0 requirements.

### ❌ Actual Behavior

{
  "dependencies": { "verify": "blocked", "archive": "blocked" },
  "nextRecommended": "resolve-review",
  "blockedReasons": [
    "bound compact post-apply gate context changed",
    "verify evidence cannot enter remediation: verify result total 11 does not match actual requirement count 0; bounded review transaction is missing"
  ],
  "remediationState": { "required": false }
}
No supported native operation clears this state: repair reports unsupported with no eligible candidates, and no lineage/receipt artifacts exist in the change root (reviewLedger/reviewReceipt/reviewBundle/reviewState all missing)

### Gentle AI Version

v2.2.4

### Operating System

Windows

### AI Agent / Client

OpenCode

### 📋 Affected Area

CLI (commands, flags)

### 💡 Logs / Error Output

```shell
See Actual Behavior above. Sanitized: no private repo names, absolute paths, credentials, or source contents included.
```

### Additional Context

Related but distinct:
- #1386 (closed): fixed the totals-mismatch stale-evidence route only when valid compact authority exists; its own text states "Without valid compact authority, behavior is unchanged" — this report is the no-authority, first-time-component variant of that gap.
- #1581 (closed): passing verify blocked by empty-vs-empty failed evidence revision mismatch — different blocker message; this occurrence is a new variant on a newer version.
- #2128 (open): archive gate blocks on invalidated receipt while review mode is disabled — not applicable here because review mode is ON.
- #1649 (open): failed verify lacking a native failed evidence revision — not applicable here because the verification PASSED.
Suggested direction (not a claim of root cause): when verification is PASS, skip failed-verification remediation entirely; and when a component project spec has never been materialized, either count requirements from the change delta spec or treat the totals comparison as non-blocking pending archive sync.

### PR DESCRIPTION
**Pull request by dnlrsls**
## 🔗 Linked Issue

Closes #2137

---

## 🏷️ PR Type

- [x] `type:bug` — Bug fix (non-breaking change that fixes an issue)
- [ ] `type:feature` — New feature (non-breaking change that adds functionality)
- [ ] `type:docs` — Documentation only
- [ ] `type:refactor` — Code refactoring (no functional changes)
- [ ] `type:chore` — Build, CI, or tooling changes
- [ ] `type:breaking-change` — Breaking change (fix or feature that changes existing behavior)

---

## 📝 Summary

- Count historical numeric `### REQ-N:` OpenSpec headings alongside canonical `### Requirement:` headings.
- Treat complete non-FAIL totals mismatches as stale verification evidence instead of failed remediation.
- Preserve approved, foreign, explicit, and disabled review-authority routing, with focused regressions and benchmark journey j44.

---

## 📂 Changes

| File / Area | What Changed |
|-------------|-------------|
| `internal/sddstatus/verification.go` | Adds conservative historical requirement-heading compatibility. |
| `internal/sddstatus/status.go` | Routes stale non-FAIL evidence through fresh review or verification without remediation. |
| `internal/sddstatus/review_gate.go` | Distinguishes blocking discovered authority from absent authority. |
| `internal/sddstatus/*_test.go` | Covers canonical/historical headings, stale PASS, genuine FAIL, and authority controls. |
| `bench/journeys_sdd.go` | Registers `j44-sdd-historical-requirement-stale-pass`. |

---

## 🧪 Test Plan

**Focused SDD status tests**
```bash
go test ./internal/sddstatus -run 'TestCountSpecRequirementsAndScenariosUsesActualArtifacts|TestResolveRoutesChangeLocalStalePassWithoutRemediation|TestResolveRoutesStaleVerifyEvidenceToVerifyUnderApprovedCompactAuthority|TestResolveRejectsForeignCompactAuthorityForStaleVerifyEvidence|TestResolveEngramRoutesStaleVerifyEvidenceToVerifyUnderApprovedCompactAuthority|TestResolveEngramRejectsForeignCompactAuthorityForStaleVerifyEvidence' -count=1
```
Result: PASS. Independent focused union including genuine FAIL, enabled, explicit, foreign, disabled/unmanaged, and archive controls also passed in 82.611s.

**Go format and build**
```bash
go run ./internal/gofmtcheck
go build -o <temp>/gentle-ai-2137.exe ./cmd/gentle-ai
git diff --check origin/main
```
Result: PASS.

**Benchmark validation**
```bash
go -C bench test -run '^TestCorpusDeclarationsAreValid$' -count=1
```
Result: PASS. The j44 declaration and causal fixture were independently inspected. Runtime execution is unavailable on this Windows host because the unchanged benchmark runner requires a POSIX execute bit; no framework-wide workaround was added.

The full `go test ./internal/sddstatus -count=1` check timed out once after 360 seconds and was not retried. Full repository unit and Docker E2E suites are left to CI.

- [ ] Unit tests pass (`go test ./...`)
- [x] Go format passes (`go run ./internal/gofmtcheck`)
- [ ] E2E tests pass (`cd e2e && ./docker-test.sh`)
- [x] Manually tested locally

---

## 🤖 Automated Checks

| Check | Status | Description |
|-------|--------|-------------|
| Check PR Cognitive Load | ⏳ | 236 changed lines, below the 400-line limit |
| Check Issue Reference | ⏳ | `Closes #2137` |
| Check Issue Has `status:approved` | ⏳ | #2137 is approved |
| Check PR Has `type:*` Label | ⏳ | `type:bug` |
| Unit Tests | ⏳ | CI |
| Go Format | ⏳ | CI |
| E2E Tests | ⏳ | CI |

---

## ✅ Contributor Checklist

- [x] PR is linked to an issue with `status:approved`
- [x] PR stays within 400 changed lines
- [x] I have added exactly one `type:*` label to this PR
- [ ] Unit tests pass (`go test ./...`)
- [x] Go format passes (`go run ./internal/gofmtcheck`)
- [ ] E2E tests pass (`cd e2e && ./docker-test.sh`)
- [x] Benchmark validation completed as described above
- [x] Documentation is not required for this internal compatibility fix
- [x] My commits follow Conventional Commits format
- [x] My commits do not include `Co-Authored-By` trailers

---

## 💬 Notes for Reviewers

The requirement-heading population is intentionally conservative: canonical `Requirement` and historical numeric `REQ-N` headings are accepted, while malformed, alphabetic, plural, and arbitrary H3 headings remain excluded. This change does not implement disabled/unmanaged FAIL remediation; that separate policy seam is tracked in #2182.

No new security, integrity, admission, repair, or governance guard is introduced. Existing explicit, foreign, approved, and disabled authority controls remain covered, and `.guard-population-baseline.txt` is unchanged.

## Summary by CodeRabbit

* **Bug Fixes**
  * Stale verification reports now require fresh verification instead of remediation.
  * Outdated passing evidence can no longer complete verification or enable archiving.
  * Stale review blockers now route to review resolution, while allowed evidence proceeds to verification.
  * Historical numbered requirement headings are now recognized during specification counting.
* **Tests**
  * Added coverage for stale evidence, review routing, failed-evidence remediation, and supported requirement heading formats.

### CODE REVIEW

File: internal/sddstatus/bounded_review_test.go [hunk 1]
```diff
@@ -910,6 +910,68 @@ func TestResolveRoutesStaleVerifyEvidenceToVerifyUnderApprovedCompactAuthority(t
...
+			}
+			if !tt.wantRemediation {
+				reasons := strings.Join(status.BlockedReasons, "\n")
+				if strings.Contains(reasons, "bounded review transaction is missing") || strings.Contains(reasons, "remediation") {
+					t.Fatalf("stale PASS entered failed-evidence routing: %v", status.BlockedReasons)
+				}
+			}
+		})
+	}
+}
```
[the remark this answers is not in the document]
Comment (dnlrsls) [reply internal/sddstatus/bounded_review_test.go:1195]: Added the stale-PASS regression with a discovered escalated native authority. It asserts resolve-review, blocked verification, and no remediation. The stale authority evaluation is also retained and reused by both status resolvers, so no second discovery is needed.

File: internal/sddstatus/status.go [hunk 2]
```diff
@@ -503,6 +519,10 @@ func Resolve(options ResolveOptions) (Status, error) {
 	if !bindingPresent {
 		if staleAllowAuthority != nil {
 			status.ReviewGate = &ReviewGateState{Result: staleAllowAuthority.Result, Reason: staleAllowAuthority.Reason}
+		} else if staleReviewAuthority != nil {
+			if status.Dependencies.Verify == DependencyAllDone && status.TaskProgress.AllComplete {
+				applyReviewGateEvaluation(&status, *staleReviewAuthority, reviewDisabled)
+			}
```
[the remark this answers is not in the document]
Comment (dnlrsls) [reply internal/sddstatus/status.go]: Implemented in ddd481f7. Both repository-local and Engram resolvers now retain the discovered stale non-allow authority in Status.ReviewGate directly, preserving the precomputed fail-closed resolve-review routing and blocked verification. The stale-PASS escalated-authority regression now asserts GateEscalated. Focused sddstatus tests, gofmtcheck, and go vet ./... pass.

File: internal/sddstatus/bounded_review_test.go [hunk 3]
```diff
@@ -1054,6 +1054,91 @@ func TestResolveRoutesStaleVerifyEvidenceToVerifyUnderApprovedCompactAuthority(t
...
+
```
[the remark this answers is not in the document]
Comment (dnlrsls) [reply internal/sddstatus/bounded_review_test.go:1196]: Implemented in 842c02a1. The stale-PASS table now covers both disabled discovered authority, which routes to `verify` with `DependencyReady` and `disabled/unmanaged`, and disabled explicit authority, which remains fail-closed at `resolve-review` with blocked verification. The same pair is covered through the Engram resolver. Focused sddstatus tests, the benchmark registry check, gofmtcheck, and go vet ./... pass.

File: internal/sddstatus/status.go [hunk 4]
```diff
@@ -418,17 +418,24 @@ func Resolve(options ResolveOptions) (Status, error) {
...
 	if !bindingPresent && reviewState == nil && applyState == ApplyAllDone && artifacts["verifyReport"] == ArtifactDone && verifyResult.Stale {
 		evaluation := resolveReviewAuthority(context.Background(), workspaceRoot, firstPath(artifactPaths.ReviewReceipt), "", changeName)
+		staleReviewAuthority = &evaluation
 		if evaluation.Result == reviewtransaction.GateAllow {
 			staleAllowAuthority = &evaluation
 		} else {
+			staleAuthorityBlocked = evaluation.Blocking
 			blockedReasons.genuine = append(blockedReasons.genuine, evaluation.Reason)
 		}
 	}
```
[the remark this answers is not in the document]
Comment (dnlrsls) [reply internal/sddstatus/status.go:562]: Implemented in 842c02a1. Both stale resolver paths now ignore a blocking evaluation only when review is disabled and the authority is absent/implicit, while retaining the authority reason for genuine blocks. Stale gate rendering now uses `applyReviewGateEvaluation`, so disabled implicit authority is reported as `disabled/unmanaged`; explicit authority still routes fail-closed. Focused sddstatus tests, the benchmark registry check, gofmtcheck, and go vet ./... pass.
