### PR TITLE
fix(review): include --committed-only in compact START rerun hint

### LINKED ISSUE #1924: fix(review): negotiated START rejects unchanged base-diff target as stale
### Pre-flight Checklist

- [x] I have searched open and closed issues and pull requests and confirmed this exact v2.2.0 regression is not already reported.
- [x] I understand that a pull request requires `status:approved` before implementation can be submitted.

### Bug Description

Gentle AI 2.2.0 can derive and persist the correct full `base-diff` snapshot with compact `review start --base-ref`, then reject the native negotiated START for that unchanged workspace with `stale_target_identity`.

The compact START freezes the expected 588-line target. The executable negotiated request preserves its returned contract, projection, and target identity, but native validation says that binding no longer matches the live workspace. The repository bytes, paths, modes, base ref, and candidate remain unchanged. Adding the original `--base-ref` to the negotiated command is not a workaround because that request is rejected as `invalid_request`.

This appears to be a residual or regression in the selector/target-binding family previously covered by closed issues #1601 and #1803, but neither issue reports this exact v2.2.0 behavior where the negotiated START carries the target and fails as stale rather than silently opening an unrelated target.

### Steps to Reproduce

1. On a feature branch with a committed diff against its parent feature branch, ensure the workspace is unchanged.
2. Run `gentle-ai review start --cwd <repo> --base-ref origin/<parent-feature-branch>`.
3. Observe a valid `base-diff` snapshot, target identity, changed-path manifest, and 588 changed lines.
4. Execute `gentle-ai review start --cwd <repo> --contract gentle-ai.review-integration/v1 --target sha256:<target> --projection workspace`.
5. Observe `stale_target_identity`, despite no candidate mutation.
6. Retry with the original `--base-ref` added and observe `invalid_request`.

### Expected Behavior

The negotiated START should create or resume authority for exactly the frozen target identity, base tree, candidate tree, paths, modes, and line count. If the base selector is required, the native transition must preserve it in a valid argument combination.

### Actual Behavior

```text
stale_target_identity
The negotiated review request no longer matches the live workspace snapshot
```

Adding the original `--base-ref` fails with `invalid_request`. The full target cannot enter review, so no valid receipt can satisfy the pre-PR lifecycle.

### Operating System

Linux

### Agent / Client

OpenCode

### Shell

bash

### Relevant Logs

```text
Gentle AI: v2.2.0
lineage: review-1a1f2df7445ac9d3
target: sha256:1a1f2df7445ac9d39182dc80800a522792ea9e164966ea39432dd6729b98c3be
changed lines: 588

negotiated START: stale_target_identity
negotiated START plus original --base-ref: invalid_request
```

### Additional Context

No candidate source, path, mode, index entry, or relevant ref changed between compact target creation and negotiated START. No authority was edited, no receipt fabricated, and no gate bypassed.

Related but not exact duplicates: #1601 and #1803 cover selector loss before START; #1692 covers VALIDATE/RECOVER; #1919, #1921, and #1656 concern different recovery or authority states.

Suggested acceptance coverage: freeze a feature-on-feature `base-diff` with `--base-ref`; execute negotiated START unchanged; assert exact target identity equality; reject genuine mutations without creating unrelated authority or a second budget.

### PR DESCRIPTION
**Pull request by ardelperal**
## 🔗 Linked Issue
Closes #1924

## 🏷️ PR Type
- [x] `type:bug` — pending maintainer (see `## Pending maintainer actions`)

## 📝 Summary
The empty-candidate receipt rerun hint (`reviewGateEmptyReceiptReason` in `internal/sddstatus/review_gate.go`) named `--base-ref <commit>` but omitted `--committed-only`. Re-running the suggested command landed on a `stale_target_identity` rejection even with an unchanged workspace, because the negotiated base-diff START validation in `validateReviewTransitionSelectorFlagCounts` (`internal/cli/review_facade.go:1684-1687`) requires both flags together. The hint now matches the validation rule and the recovery operation builder in `ReviewGateDeniedError.Error()` (`internal/cli/review.go:238-240`).

## 📂 Changes
| File | What Changed | Lines |
|------|--------------|-------|
| `internal/sddstatus/review_gate.go` | `reviewGateEmptyReceiptReason` now ends with `--base-ref <commit> --committed-only` (one-line constant change). | +1 / -1 |
| `internal/sddstatus/review_gate_reason_test.go` | New RED-first test `TestReviewGateEmptyReceiptReasonNamesBothSelectors` asserting both selectors are present and in order. | +33 / -0 |

Totals from `gh pr view --json additions,deletions,changedFiles`: **+34, -1, 2 files**.

## 🧪 Test Plan

**Local commands run (Windows):**
```bash
go test -count=1 -timeout 60s -run 'TestReviewGateEmptyReceiptReasonNamesBothSelectors' ./internal/sddstatus/...
# → ok github.com/gentleman-programming/gentle-ai/v2/internal/sddstatus 1.524s

go vet ./internal/sddstatus/...
# → exit 0

go build ./...
# → exit 0

go run ./internal/gofmtcheck
# → exit 0
```

**CI checks observed at time of body revision:**
- ✅ Go Format
- ✅ Check PR Cognitive Load
- ✅ Check Issue Reference
- ✅ Check Issue Has `status:approved`
- ✅ E2E Tests (ubuntu, arch, fedora)
- ⏳ Unit Tests, Windows Runtime, Darwin Runtime, Organic Runtime E2E — in progress

**Pre-existing test hang (not caused by this PR):**
Running `go test ./internal/sddstatus/...` with a 60s timeout on Windows hits a pre-existing 60s+ hang in an unrelated test that uses `os/exec`. Verified on the clean baseline by `git stash`-ing this change before running the package. The new test `TestReviewGateEmptyReceiptReasonNamesBothSelectors` completes in <1s in isolation. CI may need a longer per-package timeout on Windows; this is a separate issue from #1924.

## ✅ Contributor Checklist
- [x] PR linked to issue #1924 (status:approved)
- [x] PR under 400 changed lines (+34, -1)
- [x] Unit tests pass for the new test (`go test -run TestReviewGateEmptyReceiptReasonNamesBothSelectors ./internal/sddstatus/...` → ok 1.5s)
- [x] `go vet ./internal/sddstatus/...` passes
- [x] `go build ./...` passes
- [x] Go format passes (`go run ./internal/gofmtcheck`)
- [x] Conventional Commits format
- [x] No `Co-Authored-By` trailers
- [x] Branch name matches regex `fix/1924-base-diff-rerun-hint-flags`
- [ ] `type:bug` label applied — pending maintainer (see below)

## 💬 Notes for Reviewers
The fix mirrors the existing pattern in `internal/cli/review.go:238-240` and matches the negotiated base-diff START validation in `internal/cli/review_facade.go:1684-1687`. All other constant hints in `internal/sddstatus/review_gate.go` were already correct (verified by grep); this was the only orphan.

No exported items added, so docstring coverage requirement is not triggered.

## Pending maintainer actions

The following are **maintainer-applied per `pr-check.yml` and CONTRIBUTING.md** in this repo — not within contributor scope:

- [ ] `type:bug` label applied to this PR — pending Alan (verified `gh pr edit --add-label type:bug` returns 403 `AddLabelsToLabelable` for this contributor)
- [ ] Fork workflow approval — `action_required` runs on first-time forks; once approved, all subsequent runs auto-approve

### CODE REVIEW

**Comment by decode2** [comment]
Thank you for catching this. Adding `--committed-only` to the empty-receipt gate continuation is a valid improvement worth preserving. It addresses a different downstream boundary from Issue #1924, whose failure originates in the compact START hint and is addressed by PR #1931, so this PR should not close #1924.

Please open a dedicated bug issue for the empty-receipt gate hint, get it approved, then update this PR to link and close that issue and add the required `type:bug` label. Once re-scoped, this PR can be reviewed independently as a follow-up.

**Comment by dnlrsls** [comment]
Closing in favor of #1931. This patch changes an adjacent SDD receipt-gate continuation string, but it does not implement the negotiated compact START hint path reported by #1924 and lacks the executable rerun coverage present in #1931. The receipt-hint behavior should be tracked under a separate approved issue if it remains necessary.
